package com.dev.lang.semantic;

import com.dev.lang.messages.MessageLoader;
import java.text.MessageFormat;

public enum SemanticErrorCode {
	UNDEFINED_VARIABLE,
	UNDEFINED_FUNCTION,
	UNDEFINED_CLASS,
	UNDEFINED_MEMBER,
	REDEFINED_VARIABLE,
	REDEFINED_FUNCTION,
	REDEFINED_CLASS,
	REDEFINED_MEMBER,
	TYPE_MISMATCH,
	INCOMPATIBLE_TYPES,
	MISSING_RETURN,
	UNREACHABLE_CODE,
	CIRCULAR_INHERITANCE,
	INVALID_OVERRIDE,
	MISSING_IMPLEMENTATION,
	CANNOT_INSTANTIATE_ABSTRACT,
	CANNOT_INHERIT_FROM_FINAL,
	CANNOT_OVERRIDE_FINAL,
	INVALID_ACCESS,
	ARITY_MISMATCH,
	GENERIC_TYPE_MISMATCH,
	CANNOT_REDEFINE_BUILTIN;

	private static final String CATEGORY = "semantic_errors";

	public String format(Object... args) {
		return MessageLoader.formatMessage(CATEGORY, this.name(), args);
	}
}